services:
  - type: web
    name: online-mark-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_TYPE
        value: sqlite
  - type: web
    name: online-mark-frontend
    env: static
    region: singapore
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
